### PR TITLE
feat: add utnc bucket for /utnc-viz path url

### PR DESCRIPTION
**Pull request by pierreleripoll**
I woud like to add another bucket for the UTNC VIZ pilot project, so researchers could actually push all their files on the bucket and it would be served by enacit4r-cdn

### CODE REVIEW

**Comment by pierreleripoll** [comment]
@nicdub I did it partially with @guilbep , but just so you know we added a proxy_settings.conf.template so we doesn't have to rewrite every config line for both / and /utnc-viz

**Comment by pierreleripoll** [comment]
Its also nice for the future to know it's not too complicated to add separate bucket to enacit4r cdn, and it allows our users to push their data themselves without having to run/write a CLI especially for them

**Review by nicdub — COMMENTED** [review]
Nice! I am not familiar with all the nginx proxy settings so it's not easy to review, did you test it?

**Comment by pierreleripoll** [comment]
I tested it locally and it worked but maybe @guilbep can also give it a look?

**Comment by guilbep** [comment]
@pierreleripoll nice! I'm going to test it this morning! thanks

**Review by guilbep — APPROVED** [review]

**Pull request merged**
